# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Docker Compose reference guide at
# https://docs.docker.com/go/compose-spec-reference/

# Here the instructions define your application as a service called "server".
# This service is built from the Dockerfile in the current directory.
# You can add other services your application may depend on here, such as a
# database or a cache. For examples, see the Awesome Compose repository:
# https://github.com/docker/awesome-compose
services:

  # db:
  #   image: postgres:15
  #   environment:
  #     POSTGRES_DB: localhost
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: password
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - pg_data:/var/lib/postgresql/data
  # db:
  #   image: postgres
  #   restart: always
  #   user: postgres
  #   secrets:
  #     - db-password
  #   volumes:
  #     - db-data:/var/lib/postgresql
  #   environment:
  #     - POSTGRES_DB=mango
  #     - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
  #   ports:
  #     - 5432:5432
  #   healthcheck:
  #     test: [ "CMD", "pg_isready" ]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 5
    
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
      - 5431:5432
    volumes:
      - .:/app
    # depends_on:
    #   - db
    environment:
      - DB_USER=
      - DB_PASSWORD=
      - DB_HOST=
      - DB_PORT=
      - DB_NAME=
      - GENAI_API_KEY=

# volumes:
#   db-data:

# secrets:
#   # db-password:
#   #   file: .env/db_password.txt
#   api-key:
#     file: .env/api_key.txt

# volumes:
#   pg_data: